name: Delete

on:
  workflow_dispatch:

env:
  environment: dev

jobs:
  delete:
    name: Delete
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: install packages
      run: |
        npm install
        npm install -g aws-cdk

    - name: destroy app
      run: |
        cdk destroy --context ENVIRONMENT=DEV --require-approval never

